image:
  repository: 751307794059.dkr.ecr.eu-west-3.amazonaws.com/star-app-nginx:dev

ingress:
  class: nginx
  issuer: letsencrypt-dev-test
  name: ingress-star-app
  host1: "dev.star-app.xyz"
  host2: "www.dev.star-app.xyz"
  secretName: tls-secret-dev-test