image:
  repository: 751307794059.dkr.ecr.eu-west-3.amazonaws.com/star-app-nginx:release-1.0.11

ingress:
  class: nginx
  issuer: letsencrypt-test
  name: ingress-star-app
  host1: "www.star-app.xyz"
  host2: "star-app.xyz"
  secretName: tls-secret-test