image:
  repository: 751307794059.dkr.ecr.eu-west-3.amazonaws.com/star-app-nginx:latest

ingress:
  class: nginx
  issuer: letsencrypt-stg-test
  name: ingress-star-app
  host1: "stg.star-app.xyz"
  host2: "www.stg.star-app.xyz"
  secretName: tls-secret-stg-test