image:
  repository: 751307794059.dkr.ecr.eu-west-3.amazonaws.com/star-app:release-1.0.10

ingress:
  class: nginx
  issuer: letsencrypt-test
  name: ingress-star-app
  host1: "www.star-app.xyz"
  host2: "star-app.xyz"
  secretName: tls-secret-test

deployment:
  image: 751307794059.dkr.ecr.eu-west-3.amazonaws.com/star-app:release-1.0.10

secret:
  mongodburl: bW9uZ29kYjovL3Rlc3Q6dGVzdEBtb25nb2RiLXJlbGVhc2UtMC5tb25nb2RiLXJlbGVhc2UtaGVhZGxlc3M6MjcwMTcsbW9uZ29kYi1yZWxlYXNlLTEubW9uZ29kYi1yZWxlYXNlLWhlYWRsZXNzOjI3MDE3L3Jlc3RkYj9hdXRoU291cmNlPXJlc3RkYg==