image:
  repository: 751307794059.dkr.ecr.eu-west-3.amazonaws.com/star-app:latest

ingress:
  class: nginx
  issuer: letsencrypt-stg-test
  name: ingress-star-app
  host1: "stg.iiig3t-g00diii.tk"
  host2: "www.stg.iiig3t-g00diii.tk"
  secretName: tls-secret-stg-test

deployment:
  image: 751307794059.dkr.ecr.eu-west-3.amazonaws.com/star-app:latest

secret:
  mongodburl: bW9uZ29kYjovL3Rlc3Q6dGVzdEBtb25nb2RiLXN0Zy0wLm1vbmdvZGItc3RnLWhlYWRsZXNzOjI3MDE3LG1vbmdvZGItc3RnLTEubW9uZ29kYi1zdGctaGVhZGxlc3M6MjcwMTcvcmVzdGRiP2F1dGhTb3VyY2U9cmVzdGRi