apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-master-elasticsearch-master-0
  labels:
    type: local
spec:
  storageClassName: fast-disks
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"