apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.nameFile }}
data:
  nginx.conf: |
    events {}

    http {

      server {

        include /etc/nginx/mime.types;
        listen 80 default_server;
        
        location / {
          root /usr/share/nginx/html;
          try_files $uri @app;    
        }

        location @app {
          proxy_pass         http://star-app:5000;
          proxy_set_header   Host             $host;
          proxy_set_header   X-Real-IP        $remote_addr;
          proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;  
        }

      }
      
    }