apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.org/proxy-connect-timeout: '900s'
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    cert-manager.io/issuer: {{ .Values.ingress.issuer }}
  name: {{ .Values.ingress.name }}
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host1 }}
    - {{ .Values.ingress.host2 }}
    secretName: {{ .Values.ingress.secretName }}
  rules:
    - host: {{ .Values.ingress.host1 }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port: 
                  number: 80
    - host: {{ .Values.ingress.host2 }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port: 
                  number: 80