architecture: replicaset
replicaCount: 2
persistence:
  storageClass: 'standard-release'
auth:
  enabled: true
  rootPassword: other
  username: test
  password: test
  database: restdb

pvc:
  name: "standard-release"

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    additionalLabels:
      monitoring-platform: core-prometheus