architecture: replicaset
replicaCount: 2
persistence:
  storageClass: 'standard-stg'
auth:
  enabled: true
  rootPassword: other
  username: test
  password: test
  database: restdb

pvc:
  name: "standard-stg"