---
# Permit co-located instances for solitary minikube virtual machines.
antiAffinity: "soft"

# Shrink default JVM heap.
esJavaOpts: "-Xmx128m -Xms128m"

# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    cpu: "1000m"
    memory: "512M"

pvc:
  name: "standard-logging"
  annotationIsDefaultClass: "true"
  provisioner: "kubernetes.io/aws-ebs"
  type: "gp2"
  reclaimPolicy: "Delete"
  allowVolumeExpansion: "true"
  mountOptions: "debug"
  volumeBindingMode: "Immediate"

# Request smaller persistent volumes.
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "standard-logging"
  resources:
    requests:
      storage: 100M
